/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeMobileRouteImport } from './routes/knowledge.mobile'
import { Route as KnowledgeGameDevRouteImport } from './routes/knowledge.game-dev'
import { Route as KnowledgeFrontEndRouteImport } from './routes/knowledge.front-end'
import { Route as KnowledgeDatabaseRouteImport } from './routes/knowledge.database'
import { Route as KnowledgeBackEndRouteImport } from './routes/knowledge.back-end'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMobileRoute = KnowledgeMobileRouteImport.update({
  id: '/knowledge/mobile',
  path: '/knowledge/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGameDevRoute = KnowledgeGameDevRouteImport.update({
  id: '/knowledge/game-dev',
  path: '/knowledge/game-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeFrontEndRoute = KnowledgeFrontEndRouteImport.update({
  id: '/knowledge/front-end',
  path: '/knowledge/front-end',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeDatabaseRoute = KnowledgeDatabaseRouteImport.update({
  id: '/knowledge/database',
  path: '/knowledge/database',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBackEndRoute = KnowledgeBackEndRouteImport.update({
  id: '/knowledge/back-end',
  path: '/knowledge/back-end',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/knowledge/back-end': typeof KnowledgeBackEndRoute
  '/knowledge/database': typeof KnowledgeDatabaseRoute
  '/knowledge/front-end': typeof KnowledgeFrontEndRoute
  '/knowledge/game-dev': typeof KnowledgeGameDevRoute
  '/knowledge/mobile': typeof KnowledgeMobileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/knowledge/back-end': typeof KnowledgeBackEndRoute
  '/knowledge/database': typeof KnowledgeDatabaseRoute
  '/knowledge/front-end': typeof KnowledgeFrontEndRoute
  '/knowledge/game-dev': typeof KnowledgeGameDevRoute
  '/knowledge/mobile': typeof KnowledgeMobileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/knowledge/back-end': typeof KnowledgeBackEndRoute
  '/knowledge/database': typeof KnowledgeDatabaseRoute
  '/knowledge/front-end': typeof KnowledgeFrontEndRoute
  '/knowledge/game-dev': typeof KnowledgeGameDevRoute
  '/knowledge/mobile': typeof KnowledgeMobileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/knowledge/back-end'
    | '/knowledge/database'
    | '/knowledge/front-end'
    | '/knowledge/game-dev'
    | '/knowledge/mobile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/knowledge/back-end'
    | '/knowledge/database'
    | '/knowledge/front-end'
    | '/knowledge/game-dev'
    | '/knowledge/mobile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/knowledge/back-end'
    | '/knowledge/database'
    | '/knowledge/front-end'
    | '/knowledge/game-dev'
    | '/knowledge/mobile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  KnowledgeBackEndRoute: typeof KnowledgeBackEndRoute
  KnowledgeDatabaseRoute: typeof KnowledgeDatabaseRoute
  KnowledgeFrontEndRoute: typeof KnowledgeFrontEndRoute
  KnowledgeGameDevRoute: typeof KnowledgeGameDevRoute
  KnowledgeMobileRoute: typeof KnowledgeMobileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/mobile': {
      id: '/knowledge/mobile'
      path: '/knowledge/mobile'
      fullPath: '/knowledge/mobile'
      preLoaderRoute: typeof KnowledgeMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/game-dev': {
      id: '/knowledge/game-dev'
      path: '/knowledge/game-dev'
      fullPath: '/knowledge/game-dev'
      preLoaderRoute: typeof KnowledgeGameDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/front-end': {
      id: '/knowledge/front-end'
      path: '/knowledge/front-end'
      fullPath: '/knowledge/front-end'
      preLoaderRoute: typeof KnowledgeFrontEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/database': {
      id: '/knowledge/database'
      path: '/knowledge/database'
      fullPath: '/knowledge/database'
      preLoaderRoute: typeof KnowledgeDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/back-end': {
      id: '/knowledge/back-end'
      path: '/knowledge/back-end'
      fullPath: '/knowledge/back-end'
      preLoaderRoute: typeof KnowledgeBackEndRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  KnowledgeBackEndRoute: KnowledgeBackEndRoute,
  KnowledgeDatabaseRoute: KnowledgeDatabaseRoute,
  KnowledgeFrontEndRoute: KnowledgeFrontEndRoute,
  KnowledgeGameDevRoute: KnowledgeGameDevRoute,
  KnowledgeMobileRoute: KnowledgeMobileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
